services:
  # OpenAPI 파일 번들링 서비스
  # 여러 파일로 나뉜 OpenAPI 스펙을 하나의 파일로 통합
  openapi-bundler:
    build:
      context: .
      dockerfile_inline: |
        FROM node:18-alpine
        RUN npm install -g @redocly/cli
        WORKDIR /app
    volumes:
      - ./api/openapi:/app/openapi
    working_dir: /app
    command: >
      sh -c "redocly bundle ./openapi/openapi.yaml --output ./openapi/bundled-openapi.yaml &&
            echo 'Redocly 번들링 완료'"

  # ReDoc 서비스
  # API 문서를 시각적 인터페이스로 표시
  redoc:
    image: redocly/redoc:latest
    ports:
      - "8080:80"
    volumes:
      - ./api/openapi:/usr/share/nginx/html/openapi
    environment:
      - SPEC_URL=/openapi/bundled-openapi.yaml # 번들링된 파일 지정
    depends_on:
      openapi-bundler: # 번들링 서비스가 완료된 후 실행
        condition: service_completed_successfully
