openapi: 3.0.3

info:
  $ref: './info.yaml'

servers:
  - url: 'http://localhost:8080/api/v1'
    description: 'Local development server'

security:
  - AuthSession: []

components:
  securitySchemes:
    AuthSession:
      type: apiKey
      in: header
      name: Auth-Session-Id
      description: 로그인 시 발급된 인증 세션 ID

tags:
  - name: User API
    description: 사용자 계정 관리 관련 API
  - name: Auth API
    description: 로그인, 로그아웃 등 사용자 인증 관련 API
  - name: Study Group API
    description: 스터디 그룹 관련 API
  - name: Study Notice API
    description: 스터디 공지사항 관련 API

paths:
  # 사용자 API
  /users:
    post:
      $ref: './user/feature/register.yaml#/Post'
    get:
      $ref: './user/feature/search.yaml#/Get'
  /users/{userId}:
    patch:
      $ref: './user/feature/update.yaml#/Patch'
  /users/me:
    get:
      $ref: './user/feature/get-current.yaml#/Get'
  /users/{userId}/profile-image:
    post:
      $ref: './user/feature/update-profile-image.yaml#/Post'

  # 인증 API
  /auth/login:
    post:
      $ref: './auth/feature/login.yaml#/Post'
  /auth/logout:
    post:
      $ref: './auth/feature/logout.yaml#/Post'

  # 스터디 그룹 API
  /study-groups:
    post:
      $ref: './study-group/feature/create.yaml#/Post'
  /study-groups/{studyGroupId}:
    patch:
      $ref: './study-group/feature/update.yaml#/Patch'
  /study-groups/{studyGroupId}/end:
    post:
      $ref: './study-group/feature/end.yaml#/Post'
  /study-groups/{studyGroupId}/reopen:
    post:
      $ref: './study-group/feature/reopen.yaml#/Post'
  /study-groups/{studyGroupId}/membership:
    delete:
      $ref: './study-group/feature/leave.yaml#/Delete'

  # 스터디 공지사항 API
  /study-groups/{studyGroupId}/notices:
    post:
      $ref: './study-notice/feature/create.yaml#/Post'
    get:
      $ref: './study-notice/feature/list.yaml#/Get'
  /study-groups/{studyGroupId}/notices/{noticeId}:
    get:
      $ref: './study-notice/feature/get.yaml#/Get'
    patch:
      $ref: './study-notice/feature/update.yaml#/Patch'
    delete:
      $ref: './study-notice/feature/delete.yaml#/Delete'

  /study-groups/{studyGroupId}/notices/{noticeId}/pin:
    put:
      $ref: './pinned/feature/pin.yaml#/Put'
    delete:
      $ref: './pinned/feature/unpin.yaml#/Delete'

  /study-groups/{studyGroupId}/notice-pins:
    get:
      $ref: './pinned/feature/list.yaml#/Get'
