openapi: 3.0.3

info:
  $ref: './info.yaml'

servers:
  - url: 'http://localhost:8080/api/v1'
    description: 'Local development server'

paths: {}

components:
  securitySchemes:
    authSession:
      $ref: './security/auth-session.yaml'

security:
  - authSession: []
