openapi: 3.0.3

info:
  $ref: './info.yaml'

servers:
  - url: 'http://localhost:8080/api/v1'
    description: 'Local development server'

security:
  - AuthSession: []

components:
  securitySchemes:
    AuthSession:
      type: apiKey
      in: header
      name: Auth-Session-Id
      description: 로그인 시 발급된 인증 세션 ID

tags:
  - name: User API
    description: 사용자 계정 관리 관련 API
  - name: Auth API
    description: 로그인, 로그아웃 등 사용자 인증 관련 API
  - name: Study Group API
    description: 스터디 그룹 관련 API
  - name: Study Notice API
    description: 스터디 공지사항 관련 API
  - name: Image API
    description: 이미지 업로드 및 관리 관련 API
  - name: Problem API
    description: 코딩 테스트 문제 관련 API
  - name: Study Announcement API
    description: 스터디 모집 공고 관련 API
  - name: Study Application API
    description: 스터디 신청 및 지원서 관리 관련 API

paths:
  # 사용자 API
  /users:
    post:
      $ref: './user/feature/register.yaml#/Post'
    get:
      $ref: './user/feature/search.yaml#/Get'
  /users/{userId}:
    patch:
      $ref: './user/feature/update.yaml#/Patch'
  /user:
    get:
      $ref: './user/feature/get-current.yaml#/Get'

  # 인증 API
  /auth/login:
    post:
      $ref: './auth/feature/login.yaml#/Post'
  /auth/logout:
    post:
      $ref: './auth/feature/logout.yaml#/Post'

  # 스터디 그룹 API
  /study-groups:
    post:
      $ref: './study-group/feature/create.yaml#/Post'
    get:
      $ref: './study-group/feature/list.yaml#/Get'
  /study-groups/{studyGroupId}:
    patch:
      $ref: './study-group/feature/update.yaml#/Patch'
  /study-groups/{studyGroupId}/end:
    post:
      $ref: './study-group/feature/end.yaml#/Post'
  /study-groups/{studyGroupId}/reopen:
    post:
      $ref: './study-group/feature/reopen.yaml#/Post'
  /study-groups/{studyGroupId}/membership:
    delete:
      $ref: './study-group/feature/leave.yaml#/Delete'

  # 스터디 공지사항 API
  /study-groups/{studyGroupId}/notices:
    post:
      $ref: './study-notice/feature/create.yaml#/Post'
    get:
      $ref: './study-notice/feature/list.yaml#/Get'
  /study-groups/{studyGroupId}/notices/{noticeId}:
    get:
      $ref: './study-notice/feature/get.yaml#/Get'
    patch:
      $ref: './study-notice/feature/update.yaml#/Patch'
    delete:
      $ref: './study-notice/feature/delete.yaml#/Delete'
  /study-groups/{studyGroupId}/notices/{noticeId}/pin:
    put:
      $ref: './notice-pin/feature/pin.yaml#/Put'
    delete:
      $ref: './notice-pin/feature/unpin.yaml#/Delete'
  /study-groups/{studyGroupId}/notice-pins:
    get:
      $ref: './notice-pin/feature/list.yaml#/Get'

  # 이미지 API
  /images:
    post:
      $ref: './image/feature/upload.yaml#/Post'

  # 코딩테스트 문제 API
  /study-groups/{studyGroupId}/problems:
    post:
      $ref: './problem/feature/register.yaml#/Post'
    patch:
      $ref: './problem/feature/update.yaml#/Patch'
    delete:
      $ref: './problem/feature/delete.yaml#/Delete'

  # 스터디 모집 공고 API
  /announcements:
    post:
      $ref: './study-announcement/feature/create.yaml#/Post'
    get:
      $ref: './study-announcement/feature/list.yaml#/Get'
  /announcements/{announcementId}:
    get:
      $ref: './study-announcement/feature/get.yaml#/Get'
    patch:
      $ref: './study-announcement/feature/update.yaml#/Patch'
    delete:
      $ref: './study-announcement/feature/delete.yaml#/Delete'
  /announcements/{announcementId}/close:
    post:
      $ref: './study-announcement/feature/close.yaml#/Post'

  # 스터디 신청서 API
  /applications:
    post:
      $ref: './study-application/feature/submit.yaml#/Post'
  /applications/{applicationId}:
    get:
      $ref: './study-application/feature/get.yaml#/Get'
    patch:
      $ref: './study-application/feature/update.yaml#/Patch'
    delete:
      $ref: './study-application/feature/cancel.yaml#/Delete'
  /user/applications:
    get:
      $ref: './study-application/feature/list-my.yaml#/Get'
  /announcements/{announcementId}/applications:
    get:
      $ref: './study-application/feature/list-announcement.yaml#/Get'
  /applications/{applicationId}/start-review:
    post:
      $ref: './study-application/feature/start-review.yaml#/Post'
  /applications/{applicationId}/approve:
    post:
      $ref: './study-application/feature/approve.yaml#/Post'
  /applications/{applicationId}/reject:
    post:
      $ref: './study-application/feature/reject.yaml#/Post'
