openapi: 3.0.3

info:
  $ref: './info.yaml'

servers:
  - url: 'http://localhost:8080/api/v1'
    description: 'Local development server'

security:
  - NubbleAuth: []

components:
  securitySchemes:
    NubbleAuth:
      type: apiKey
      in: header
      name: Auth-Session-Id
      description: 로그인 시 발급된 인증 세션 ID

paths:
  # 사용자 API
  /users:
    $ref: './user/feature/register.yaml#/Path'
