openapi: 3.0.3

info:
  $ref: './info.yaml'

servers:
  - url: 'http://localhost:8080/api/v1'
    description: 'Local development server'

security:
  - AuthSession: []

components:
  securitySchemes:
    AuthSession:
      type: apiKey
      in: header
      name: Auth-Session-Id
      description: 로그인 시 발급된 인증 세션 ID

paths:
  # 사용자 API
  /users:
    post:
      $ref: './user/feature/register.yaml#/Post'
    get:
      $ref: './user/feature/search.yaml#/Get'

  # 인증 API
  /auth/login:
    post:
      $ref: './auth/feature/login.yaml#/Post'
  /auth/logout:
      post:
        $ref: './auth/feature/logout.yaml#/Post'
